In [2]:
import numpy as np 

In [3]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
one_dimensional_array

array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])

In [4]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
two_dimensional_array

array([[ 6,  5],
       [11,  7],
       [ 4,  8]])

In [5]:
zero_array = np.zeros((2,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
one_array = np.ones((4,6))
one_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
sequence_of_integers = np.arange(5, 12)
sequence_of_integers

array([ 5,  6,  7,  8,  9, 10, 11])

In [8]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
random_integers_between_50_and_100

array([99, 99, 51, 87, 61, 77])

In [9]:
random_floats_between_0_and_1 = np.random.random([6])
random_floats_between_0_and_1

array([0.85209682, 0.19618331, 0.42193098, 0.20110758, 0.77622918,
       0.29816542])

In [10]:
random_matrix = np.random.random([2,3])
random_matrix

array([[0.68692764, 0.70478227, 0.4792501 ],
       [0.35751988, 0.71876031, 0.59043091]])

In [11]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
random_floats_between_2_and_3

array([2.85209682, 2.19618331, 2.42193098, 2.20110758, 2.77622918,
       2.29816542])

In [12]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
random_integers_between_150_and_300

array([297, 297, 153, 261, 183, 231])

Task 1

In [23]:
features = np.arange(6, 21)
label = features * 3 + 4

features
label

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

Task 2

In [24]:
noise = np.random.random([15])*4-2
label = label + noise

label
noise

array([-0.64566381, -0.91287097, -0.45956971, -0.38768187,  0.79225752,
        0.24832493,  0.8412128 , -0.27512461,  0.91599136, -0.54380466,
        0.91193217, -1.97662863, -1.01306755, -1.16722389,  0.04122469])

Task 3

In [26]:
np.random.randint(low=1, high=500, size=(20, 5))

array([[106, 375, 201, 370, 198],
       [144, 215,   5, 217,  55],
       [269,  74, 139,  46, 473],
       [356, 317, 169, 203,  95],
       [ 20, 108, 324, 388, 251],
       [211, 173,  98, 362, 444],
       [310, 227, 396,  11, 491],
       [368, 408, 119, 186, 291],
       [117,  23, 278, 344,  67],
       [408, 455, 345,  81, 192],
       [301, 277, 177,  22, 116],
       [430, 296, 116,  33, 322],
       [179, 488, 116, 492, 354],
       [346, 102, 155, 441,  92],
       [142, 177, 443, 300, 259],
       [407, 192,   7, 103, 396],
       [ 56, 420, 300,  88,  77],
       [188, 178, 108, 377, 333],
       [496, 176,  42, 442, 251],
       [470, 121,  54,  53, 165]])