In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

In [5]:
loc = pd.read_excel("locationdensity.xlsx")["grid_code"]

0      0.154119
1      0.025741
2      0.025741
3      0.025741
4      0.042463
         ...   
359    0.085954
360    0.085954
361    0.085954
362    0.085954
363    0.085954
Name: grid_code, Length: 364, dtype: float64

In [23]:
dist = {}
for i in range(len(loc)):
    if i < 263:
        dist[str(i//21+1) + "," + str(i%21+1)] = loc[i]

    elif i < 272:
        dist[str(13) + "," + str((i+1)%21+1)] = loc[i]

    elif i < 284:
        dist[str(14) + "," + str((i+1)%21+1)] = loc[i]
    elif i < 289:
        dist[str(14) + "," + str((i+5)%21+1)] = loc[i]

    elif i < 302:
        dist[str(15) + "," + str((i+7)%21+1)] = loc[i]
    elif i < 307:
        dist[str(15) + "," + str((i+8)%21+1)] = loc[i]

    elif i < 312:
        dist[str(16) + "," + str((i+12)%21+1)] = loc[i]
    elif i < 314:
        dist[str(16) + "," + str((i+13)%21+1)] = loc[i]
    elif i < 316:
        dist[str(16) + "," + str((i+14)%21+1)] = loc[i]
    elif i < 319:
        dist[str(16) + "," + str((i+15)%21+1)] = loc[i]
    elif i < 320:
        dist[str(16) + "," + str((i+16)%21+1)] = loc[i]

    elif i < 325:
        dist[str(17) + "," + str((i+22)%21+1)] = loc[i]
    elif i < 328:
        dist[str(17) + "," + str((i+29)%21+1)] = loc[i]

    elif i < 331:
        dist[str(18) + "," + str((i+37)%21+1)] = loc[i]
    elif i < 332:
        dist[str(18) + "," + str((i+40)%21+1)] = loc[i]
    elif i < 333:
        dist[str(18) + "," + str((i+45)%21+1)] = loc[i]

    elif i < 341:
        dist[str(19) + "," + str((i+54)%21+1)] = loc[i]
    elif i < 342:
        dist[str(19) + "," + str((i+57)%21+1)] = loc[i]

    elif i < 348:
        dist[str(20) + "," + str((i+68)%21+1)] = loc[i]

    elif i < 353:
        dist[str(21) + "," + str((i+84)%21+1)] = loc[i]

    elif i < 355:
        dist[str(22) + "," + str((i+101)%21+1)] = loc[i]

    elif i < 357:
        dist[str(23) + "," + str((i+123)%21+1)] = loc[i]

    elif i < 362:
        dist[str(24) + "," + str((i+141)%21+1)] = loc[i]

    elif i < 364:
        dist[str(25) + "," + str((i+159)%21+1)] = loc[i]

dist.keys()

dict_keys(['1,1', '1,2', '1,3', '1,4', '1,5', '1,6', '1,7', '1,8', '1,9', '1,10', '1,11', '1,12', '1,13', '1,14', '1,15', '1,16', '1,17', '1,18', '1,19', '1,20', '1,21', '2,1', '2,2', '2,3', '2,4', '2,5', '2,6', '2,7', '2,8', '2,9', '2,10', '2,11', '2,12', '2,13', '2,14', '2,15', '2,16', '2,17', '2,18', '2,19', '2,20', '2,21', '3,1', '3,2', '3,3', '3,4', '3,5', '3,6', '3,7', '3,8', '3,9', '3,10', '3,11', '3,12', '3,13', '3,14', '3,15', '3,16', '3,17', '3,18', '3,19', '3,20', '3,21', '4,1', '4,2', '4,3', '4,4', '4,5', '4,6', '4,7', '4,8', '4,9', '4,10', '4,11', '4,12', '4,13', '4,14', '4,15', '4,16', '4,17', '4,18', '4,19', '4,20', '4,21', '5,1', '5,2', '5,3', '5,4', '5,5', '5,6', '5,7', '5,8', '5,9', '5,10', '5,11', '5,12', '5,13', '5,14', '5,15', '5,16', '5,17', '5,18', '5,19', '5,20', '5,21', '6,1', '6,2', '6,3', '6,4', '6,5', '6,6', '6,7', '6,8', '6,9', '6,10', '6,11', '6,12', '6,13', '6,14', '6,15', '6,16', '6,17', '6,18', '6,19', '6,20', '6,21', '7,1', '7,2', '7,3', '7,4', '7,5', 

In [27]:
locationlist = []
for key in dist.keys():
    key1 = key.split(",")
    locationlist.append(np.asarray([int(key1[0]), int(key1[1])]))

locationlist

[array([1, 1]),
 array([1, 2]),
 array([1, 3]),
 array([1, 4]),
 array([1, 5]),
 array([1, 6]),
 array([1, 7]),
 array([1, 8]),
 array([1, 9]),
 array([ 1, 10]),
 array([ 1, 11]),
 array([ 1, 12]),
 array([ 1, 13]),
 array([ 1, 14]),
 array([ 1, 15]),
 array([ 1, 16]),
 array([ 1, 17]),
 array([ 1, 18]),
 array([ 1, 19]),
 array([ 1, 20]),
 array([ 1, 21]),
 array([2, 1]),
 array([2, 2]),
 array([2, 3]),
 array([2, 4]),
 array([2, 5]),
 array([2, 6]),
 array([2, 7]),
 array([2, 8]),
 array([2, 9]),
 array([ 2, 10]),
 array([ 2, 11]),
 array([ 2, 12]),
 array([ 2, 13]),
 array([ 2, 14]),
 array([ 2, 15]),
 array([ 2, 16]),
 array([ 2, 17]),
 array([ 2, 18]),
 array([ 2, 19]),
 array([ 2, 20]),
 array([ 2, 21]),
 array([3, 1]),
 array([3, 2]),
 array([3, 3]),
 array([3, 4]),
 array([3, 5]),
 array([3, 6]),
 array([3, 7]),
 array([3, 8]),
 array([3, 9]),
 array([ 3, 10]),
 array([ 3, 11]),
 array([ 3, 12]),
 array([ 3, 13]),
 array([ 3, 14]),
 array([ 3, 15]),
 array([ 3, 16]),
 array([ 3

In [25]:
def probfunx(d):
    return(1/(1+np.exp(d))*2)

In [43]:
df = pd.DataFrame(columns=["Location", "Value"])

for i in locationlist:
    currsum = 0
    for j in locationlist:
        currsum += probfunx(np.linalg.norm(i-j)) * dist[str(j[0]) + "," + str(j[1])]
    df.loc[len(df)] = [i, currsum]

#print(maxloc, max2loc, max3loc, max4loc, max5loc)
df = df.sort_values("Value", ascending=False).reset_index(drop=True)
df.to_excel("optimallocations.xlsx")

In [53]:
df2 = pd.DataFrame(columns=["Location 1", "Location 2", "Value"])

for i in range(len(locationlist)):
    maxsum = 0
    maxj = 0
    for j in range(i,len(locationlist)):
        currsum = 0
        for k in locationlist:   
            currsum += probfunx(min(np.linalg.norm(locationlist[i]-k), np.linalg.norm(locationlist[j]-k))) * dist[str(k[0]) + "," + str(k[1])]
        if currsum > maxsum:
            maxsum = currsum
            maxj = j
    df2.loc[len(df2)] = [locationlist[i], locationlist[maxj], maxsum]
    print(locationlist[i])

[1 1]
[1 2]
[1 3]
[1 4]
[1 5]
[1 6]
[1 7]
[1 8]
[1 9]
[ 1 10]
[ 1 11]
[ 1 12]
[ 1 13]
[ 1 14]
[ 1 15]
[ 1 16]
[ 1 17]
[ 1 18]
[ 1 19]
[ 1 20]
[ 1 21]
[2 1]
[2 2]
[2 3]
[2 4]
[2 5]
[2 6]
[2 7]
[2 8]
[2 9]
[ 2 10]
[ 2 11]
[ 2 12]
[ 2 13]
[ 2 14]
[ 2 15]
[ 2 16]
[ 2 17]
[ 2 18]
[ 2 19]
[ 2 20]
[ 2 21]
[3 1]
[3 2]
[3 3]
[3 4]
[3 5]
[3 6]
[3 7]
[3 8]
[3 9]
[ 3 10]
[ 3 11]
[ 3 12]
[ 3 13]
[ 3 14]
[ 3 15]
[ 3 16]
[ 3 17]
[ 3 18]
[ 3 19]
[ 3 20]
[ 3 21]
[4 1]
[4 2]
[4 3]
[4 4]
[4 5]
[4 6]
[4 7]
[4 8]
[4 9]
[ 4 10]
[ 4 11]
[ 4 12]
[ 4 13]
[ 4 14]
[ 4 15]
[ 4 16]
[ 4 17]
[ 4 18]
[ 4 19]
[ 4 20]
[ 4 21]
[5 1]
[5 2]
[5 3]
[5 4]
[5 5]
[5 6]
[5 7]
[5 8]
[5 9]
[ 5 10]
[ 5 11]
[ 5 12]
[ 5 13]
[ 5 14]
[ 5 15]
[ 5 16]
[ 5 17]
[ 5 18]
[ 5 19]
[ 5 20]
[ 5 21]
[6 1]
[6 2]
[6 3]
[6 4]
[6 5]
[6 6]
[6 7]
[6 8]
[6 9]
[ 6 10]
[ 6 11]
[ 6 12]
[ 6 13]
[ 6 14]
[ 6 15]
[ 6 16]
[ 6 17]
[ 6 18]
[ 6 19]
[ 6 20]
[ 6 21]
[7 1]
[7 2]
[7 3]
[7 4]
[7 5]
[7 6]
[7 7]
[7 8]
[7 9]
[ 7 10]
[ 7 11]
[ 7 12]
[ 7 13]
[ 7 14]
[ 7 15

In [54]:
df2 = df2.sort_values("Value", ascending=False).reset_index(drop=True)
df2.to_excel("optimallocations2.xlsx")
df2

Location 1 Location 2      Value
0     [10, 15]    [11, 9]  20.510924
1      [10, 9]   [12, 13]  20.448056
2      [11, 9]   [11, 15]  20.384243
3     [11, 10]   [11, 15]  20.356561
4     [10, 14]    [11, 9]  20.256634
..         ...        ...        ...
359   [24, 18]   [24, 19]   0.492960
360   [24, 19]   [25, 18]   0.433298
361   [24, 20]   [25, 18]   0.416566
362   [25, 18]   [25, 19]   0.401167
363   [25, 19]   [25, 19]   0.305193

[364 rows x 3 columns]

In [2]:
import numpy as np

In [54]:
tmaxtrix1 = np.matrix([[.896, .104, 0, 0, 0, 0], [0, .713, .287, 0, 0, 0], [0, 0, .385, .11, .50, .005], [.40, 0, .60, 0, 0, 0], [0,0,0,.11,.89,0], [0, 0, 0, 0, 0, 1]]).getT()
tmaxtrix2 = np.matrix([[.896, .104, 0, 0, 0], [0, .713, .287, 0, 0], [0, 0, .885, .11, .005], [.40, 0, .60, 0, 0], [0, 0, 0, 0, 1]]).getT()

vec1 = np.matrix([1, 0, 0, 0, 0, 0]).getT()
vec2 = np.matrix([1, 0, 0, 0, 0]).getT()

In [57]:
np.matmul(np.linalg.matrix_power(tmaxtrix1, 20), vec1)

matrix([[0.2650528 ],
        [0.10576045],
        [0.11006819],
        [0.06081272],
        [0.44872206],
        [0.00958378]])